#!/bin/bash
source $(dirname $BASH_SOURCE)/source

# change directory to server files
cd "$MINECRAFT_DIR/server"

# start the Minecraft server in a screen instance
echo "screen -DmS $MINECRAFT_ID /bin/java -Xms$MINECRAFT_MIN -Xmx$MINECRAFT_MAX -jar $MINECRAFT_JAR nogui"
