#!/bin/bash
source $(dirname $BASH_SOURCE)/source

# change directory to server files
cd $MINECRAFT_SERVER_DIR

# start the Minecraft server in a screen instance
screen -DmS $MINECRAFT_ID java -Xms$MINECRAFT_MIN -Xmx$MINECRAFT_MAX -jar $MINECRAFT_JAR nogui
