#!/bin/bash

# server
MINECRAFT_ID="niner-miners-minecraft-server"
MINECRAFT_DIR="$HOME/minecraft"
MINECRAFT_JAR="$MINECRAFT_DIR/server/spigot.jar"
MINECRAFT_MIN="1024M"
MINECRAFT_MAX="3072M"
MINECRAFT_TILES="server/plugins/dynmap/web/tiles/**\*"

# backup
AWS_S3_BUCKET="s3://niner-miners-minecraft/"
BACKUP_LOG="$MINECRAFT_DIR/backup.log"

# tunnel
TUNNEL_USER="guest"
TUNNEL_HOST="nickbreaton.com"
TUNNEL_MONITOR_PORT="60101"
TUNNEL_PORT_MAP=(
  "22"      "60122"    # SSH
  "8123"    "50100"    # Dynmap
  "25565"   "60100"    # Minecraft
)