#!/bin/bash
source $(dirname $BASH_SOURCE)/source

for i in "${!TUNNEL_PORT_MAP[@]}"; do
  if ! ((i % 2)); then
    TUNNELS="-R ${TUNNEL_PORT_MAP[((i + 1))]}:localhost:${TUNNEL_PORT_MAP[$i]} $TUNNELS"
  fi
done

echo "autossh $TUNNELS -M $TUNNEL_MONITOR_PORT -N $TUNNEL_USER@$TUNNEL_HOST"
