#!/bin/bash
source $(dirname $(dirname $BASH_SOURCE))/CONFIG

# log start time
echo "START: $(date)" > $BACKUP_LOG
echo "" >> $BACKUP_LOG

# log AWS output
aws s3 sync $MINECRAFT_DIR $AWS_S3_BUCKET --exclude $MINECRAFT_TILES --delete

# log end time
echo "" >> $BACKUP_LOG
echo "FINISH: $(date)" >> $BACKUP_LOG
