#!/bin/bash
source $(dirname $(dirname $BASH_SOURCE))/CONFIG

# log start time
echo "START: $(DATE)" > $BACKUP_LOG
echo "" >> $BACKUP_LOG

# log AWS output
echo $(aws s3 sync $MINECRAFT_DIR $AWS_S3_BUCKET --exclude $MINECRAFT_TILES) >> $BACKUP_LOG

# log end time
echo "" >> $BACKUP_LOG
echo "FINISH: $(DATE)" >> $BACKUP_LOG
