#!/bin/bash
source $(dirname $(dirname $BASH_SOURCE))/CONFIG

# generate temporary location
TMP=/tmp/niner-miners-tiles-$(uuidgen)

# move tiles to temp location to exclude from sync
mv $MINECRAFT_TILES $TMP;

# start and stop dropbox sync
dropbox start;
while [ "$(dropbox status)" != "Up to date" ]; do
  dropbox status;
  sleep 1;
done;
dropbox stop;

# return tiles back to permanent home
mv $TMP $MINECRAFT_TILES;
